/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BookingSlugRouteImport } from './routes/booking.$slug'
import { Route as AuthenticatedSaasRouteImport } from './routes/_authenticated/saas'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppRelatoriosRouteImport } from './routes/_authenticated/app.relatorios'
import { Route as AuthenticatedAppEstoqueRouteImport } from './routes/_authenticated/app.estoque'
import { Route as AuthenticatedAppConfiguracoesRouteImport } from './routes/_authenticated/app.configuracoes'
import { Route as AuthenticatedAppComissoesRouteImport } from './routes/_authenticated/app.comissoes'
import { Route as AuthenticatedAppComandasRouteImport } from './routes/_authenticated/app.comandas'
import { Route as AuthenticatedAppCaixaRouteImport } from './routes/_authenticated/app.caixa'
import { Route as AuthenticatedAppCadastrosRouteImport } from './routes/_authenticated/app.cadastros'
import { Route as AuthenticatedAppAssinaturaRouteImport } from './routes/_authenticated/app.assinatura'
import { Route as AuthenticatedAppAssinantesRouteImport } from './routes/_authenticated/app.assinantes'
import { Route as AuthenticatedAppAgendaRouteImport } from './routes/_authenticated/app.agenda'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingSlugRoute = BookingSlugRouteImport.update({
  id: '/booking/$slug',
  path: '/booking/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSaasRoute = AuthenticatedSaasRouteImport.update({
  id: '/saas',
  path: '/saas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppRelatoriosRoute =
  AuthenticatedAppRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEstoqueRoute = AuthenticatedAppEstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppConfiguracoesRoute =
  AuthenticatedAppConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComissoesRoute =
  AuthenticatedAppComissoesRouteImport.update({
    id: '/comissoes',
    path: '/comissoes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppComandasRoute =
  AuthenticatedAppComandasRouteImport.update({
    id: '/comandas',
    path: '/comandas',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppCaixaRoute = AuthenticatedAppCaixaRouteImport.update({
  id: '/caixa',
  path: '/caixa',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppCadastrosRoute =
  AuthenticatedAppCadastrosRouteImport.update({
    id: '/cadastros',
    path: '/cadastros',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAssinaturaRoute =
  AuthenticatedAppAssinaturaRouteImport.update({
    id: '/assinatura',
    path: '/assinatura',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAssinantesRoute =
  AuthenticatedAppAssinantesRouteImport.update({
    id: '/assinantes',
    path: '/assinantes',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAgendaRoute = AuthenticatedAppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/saas': typeof AuthenticatedSaasRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/assinantes': typeof AuthenticatedAppAssinantesRoute
  '/app/assinatura': typeof AuthenticatedAppAssinaturaRoute
  '/app/cadastros': typeof AuthenticatedAppCadastrosRoute
  '/app/caixa': typeof AuthenticatedAppCaixaRoute
  '/app/comandas': typeof AuthenticatedAppComandasRoute
  '/app/comissoes': typeof AuthenticatedAppComissoesRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/saas': typeof AuthenticatedSaasRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/app/assinantes': typeof AuthenticatedAppAssinantesRoute
  '/app/assinatura': typeof AuthenticatedAppAssinaturaRoute
  '/app/cadastros': typeof AuthenticatedAppCadastrosRoute
  '/app/caixa': typeof AuthenticatedAppCaixaRoute
  '/app/comandas': typeof AuthenticatedAppComandasRoute
  '/app/comissoes': typeof AuthenticatedAppComissoesRoute
  '/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/app': typeof AuthenticatedAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/saas': typeof AuthenticatedSaasRoute
  '/booking/$slug': typeof BookingSlugRoute
  '/_authenticated/app/agenda': typeof AuthenticatedAppAgendaRoute
  '/_authenticated/app/assinantes': typeof AuthenticatedAppAssinantesRoute
  '/_authenticated/app/assinatura': typeof AuthenticatedAppAssinaturaRoute
  '/_authenticated/app/cadastros': typeof AuthenticatedAppCadastrosRoute
  '/_authenticated/app/caixa': typeof AuthenticatedAppCaixaRoute
  '/_authenticated/app/comandas': typeof AuthenticatedAppComandasRoute
  '/_authenticated/app/comissoes': typeof AuthenticatedAppComissoesRoute
  '/_authenticated/app/configuracoes': typeof AuthenticatedAppConfiguracoesRoute
  '/_authenticated/app/estoque': typeof AuthenticatedAppEstoqueRoute
  '/_authenticated/app/relatorios': typeof AuthenticatedAppRelatoriosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/app'
    | '/saas'
    | '/booking/$slug'
    | '/app/agenda'
    | '/app/assinantes'
    | '/app/assinatura'
    | '/app/cadastros'
    | '/app/caixa'
    | '/app/comandas'
    | '/app/comissoes'
    | '/app/configuracoes'
    | '/app/estoque'
    | '/app/relatorios'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/saas'
    | '/booking/$slug'
    | '/app/agenda'
    | '/app/assinantes'
    | '/app/assinatura'
    | '/app/cadastros'
    | '/app/caixa'
    | '/app/comandas'
    | '/app/comissoes'
    | '/app/configuracoes'
    | '/app/estoque'
    | '/app/relatorios'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app'
    | '/_authenticated/saas'
    | '/booking/$slug'
    | '/_authenticated/app/agenda'
    | '/_authenticated/app/assinantes'
    | '/_authenticated/app/assinatura'
    | '/_authenticated/app/cadastros'
    | '/_authenticated/app/caixa'
    | '/_authenticated/app/comandas'
    | '/_authenticated/app/comissoes'
    | '/_authenticated/app/configuracoes'
    | '/_authenticated/app/estoque'
    | '/_authenticated/app/relatorios'
    | '/_authenticated/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookingSlugRoute: typeof BookingSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking/$slug': {
      id: '/booking/$slug'
      path: '/booking/$slug'
      fullPath: '/booking/$slug'
      preLoaderRoute: typeof BookingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/saas': {
      id: '/_authenticated/saas'
      path: '/saas'
      fullPath: '/saas'
      preLoaderRoute: typeof AuthenticatedSaasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/relatorios': {
      id: '/_authenticated/app/relatorios'
      path: '/relatorios'
      fullPath: '/app/relatorios'
      preLoaderRoute: typeof AuthenticatedAppRelatoriosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/estoque': {
      id: '/_authenticated/app/estoque'
      path: '/estoque'
      fullPath: '/app/estoque'
      preLoaderRoute: typeof AuthenticatedAppEstoqueRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/configuracoes': {
      id: '/_authenticated/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AuthenticatedAppConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comissoes': {
      id: '/_authenticated/app/comissoes'
      path: '/comissoes'
      fullPath: '/app/comissoes'
      preLoaderRoute: typeof AuthenticatedAppComissoesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/comandas': {
      id: '/_authenticated/app/comandas'
      path: '/comandas'
      fullPath: '/app/comandas'
      preLoaderRoute: typeof AuthenticatedAppComandasRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/caixa': {
      id: '/_authenticated/app/caixa'
      path: '/caixa'
      fullPath: '/app/caixa'
      preLoaderRoute: typeof AuthenticatedAppCaixaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/cadastros': {
      id: '/_authenticated/app/cadastros'
      path: '/cadastros'
      fullPath: '/app/cadastros'
      preLoaderRoute: typeof AuthenticatedAppCadastrosRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assinatura': {
      id: '/_authenticated/app/assinatura'
      path: '/assinatura'
      fullPath: '/app/assinatura'
      preLoaderRoute: typeof AuthenticatedAppAssinaturaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/assinantes': {
      id: '/_authenticated/app/assinantes'
      path: '/assinantes'
      fullPath: '/app/assinantes'
      preLoaderRoute: typeof AuthenticatedAppAssinantesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/agenda': {
      id: '/_authenticated/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AuthenticatedAppAgendaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
  }
}

interface AuthenticatedAppRouteChildren {
  AuthenticatedAppAgendaRoute: typeof AuthenticatedAppAgendaRoute
  AuthenticatedAppAssinantesRoute: typeof AuthenticatedAppAssinantesRoute
  AuthenticatedAppAssinaturaRoute: typeof AuthenticatedAppAssinaturaRoute
  AuthenticatedAppCadastrosRoute: typeof AuthenticatedAppCadastrosRoute
  AuthenticatedAppCaixaRoute: typeof AuthenticatedAppCaixaRoute
  AuthenticatedAppComandasRoute: typeof AuthenticatedAppComandasRoute
  AuthenticatedAppComissoesRoute: typeof AuthenticatedAppComissoesRoute
  AuthenticatedAppConfiguracoesRoute: typeof AuthenticatedAppConfiguracoesRoute
  AuthenticatedAppEstoqueRoute: typeof AuthenticatedAppEstoqueRoute
  AuthenticatedAppRelatoriosRoute: typeof AuthenticatedAppRelatoriosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedAppAgendaRoute: AuthenticatedAppAgendaRoute,
  AuthenticatedAppAssinantesRoute: AuthenticatedAppAssinantesRoute,
  AuthenticatedAppAssinaturaRoute: AuthenticatedAppAssinaturaRoute,
  AuthenticatedAppCadastrosRoute: AuthenticatedAppCadastrosRoute,
  AuthenticatedAppCaixaRoute: AuthenticatedAppCaixaRoute,
  AuthenticatedAppComandasRoute: AuthenticatedAppComandasRoute,
  AuthenticatedAppComissoesRoute: AuthenticatedAppComissoesRoute,
  AuthenticatedAppConfiguracoesRoute: AuthenticatedAppConfiguracoesRoute,
  AuthenticatedAppEstoqueRoute: AuthenticatedAppEstoqueRoute,
  AuthenticatedAppRelatoriosRoute: AuthenticatedAppRelatoriosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedSaasRoute: typeof AuthenticatedSaasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedSaasRoute: AuthenticatedSaasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  BookingSlugRoute: BookingSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
