// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const AUTH_TAB_ID_KEY = 'linkup-studio:auth-tab-id';
const AUTH_STORAGE_PREFIX = 'linkup-studio-auth';

function createAuthContextId() {
  if (typeof crypto !== 'undefined' && typeof crypto.randomUUID === 'function') {
    return crypto.randomUUID();
  }
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2)}`;
}

function isStandalonePwa() {
  if (typeof window === 'undefined') return false;
  const nav = window.navigator as Navigator & { standalone?: boolean };
  return window.matchMedia?.('(display-mode: standalone)').matches || nav.standalone === true;
}

function bookingSlugFromPath(pathname: string) {
  const [, slug] = pathname.match(/^\/booking\/([^/?#]+)/) ?? [];
  return slug ? decodeURIComponent(slug) : 'booking';
}

function surfaceFromRoute(pathname: string, searchParams: URLSearchParams) {
  if (pathname === '/auth') {
    const redirect = searchParams.get('redirect');
    if (redirect) {
      try {
        const redirectUrl = new URL(redirect, window.location.origin);
        return surfaceFromRoute(redirectUrl.pathname, redirectUrl.searchParams);
      } catch {
        if (redirect.startsWith('/booking')) return `booking:${bookingSlugFromPath(redirect)}`;
      }
    }
  }

  if (pathname === '/booking' || pathname.startsWith('/booking/')) {
    return `booking:${bookingSlugFromPath(pathname)}`;
  }

  const tenantSlug = searchParams.get('tenant');
  return tenantSlug ? `admin:${tenantSlug}` : 'admin';
}

function getBrowserAuthStorage() {
  if (typeof window === 'undefined') return undefined;
  return isStandalonePwa() ? window.localStorage : window.sessionStorage;
}

function getBrowserAuthStorageKey() {
  if (typeof window === 'undefined') return `${AUTH_STORAGE_PREFIX}:server`;

  const surface = surfaceFromRoute(window.location.pathname, new URLSearchParams(window.location.search));
  if (isStandalonePwa()) return `${AUTH_STORAGE_PREFIX}:${surface}`;

  let tabId = window.sessionStorage.getItem(AUTH_TAB_ID_KEY);
  if (!tabId) {
    tabId = createAuthContextId();
    window.sessionStorage.setItem(AUTH_TAB_ID_KEY, tabId);
  }
  return `${AUTH_STORAGE_PREFIX}:${surface}:tab:${tabId}`;
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || process.env.SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || process.env.SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: getBrowserAuthStorage(),
      storageKey: getBrowserAuthStorageKey(),
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

